export const projects = [
  {
    slug: 'ma-store',
    index: '01',
    name: 'DAR GROUP',
    meta: 'CORPORATE × UX/UI × WEB',
    year: '2026',
    industry: 'Retail / Fashion',
    industryRu: 'Ритейл / Мода',
    services: 'UX/UI / Frontend / E-commerce',
    servicesRu: 'UX/UI / Фронтенд / E-commerce',
    intro: 'Digital storefront built around a clean catalogue, strong product presentation and frictionless purchase flow.',
    introRu: 'Цифровой магазин с чистым каталогом, сильной подачей товаров и удобным процессом покупки.',
    challenge: 'Create a modern e-commerce experience that feels premium without becoming decorative or difficult to use.',
    challengeRu: 'Создать современный e-commerce с премиальным ощущением — без лишней декоративности и сложности в использовании.',
    solution: [
      ['UX ARCHITECTURE', 'Restructured catalogue, navigation and product paths around fast decision making.'],
      ['VISUAL SYSTEM', 'Built a restrained interface language where product content remains the hero.'],
      ['DEVELOPMENT', 'Created a responsive component system ready for growth and new collections.'],
    ],
    solutionRu: [
      ['UX-АРХИТЕКТУРА', 'Перестроили каталог, навигацию и пути к товарам для быстрого принятия решений.'],
      ['ВИЗУАЛЬНАЯ СИСТЕМА', 'Создали сдержанный интерфейсный язык, где контент остаётся главным.'],
      ['РАЗРАБОТКА', 'Создали адаптивную компонентную систему, готовую к росту и новым коллекциям.'],
    ],
    outcomes: ['SCALABLE UI SYSTEM', 'RESPONSIVE STORE', 'FASTER PRODUCT DISCOVERY'],
    outcomesRu: ['МАСШТАБИРУЕМАЯ UI-СИСТЕМА', 'АДАПТИВНЫЙ МАГАЗИН', 'БЫСТРЫЙ ПОИСК ТОВАРОВ'],
    visual: 'visual-a',
  },
  {
    slug: 'jaryq-home',
    index: '02',
    name: 'JARYQ HOME',
    meta: 'CONSTRUCTION × UX/UI × WEB',
    year: '2026',
    industry: 'Construction / Glazing',
    industryRu: 'Строительство / Остекление',
    services: 'Web Design / UI / Landing',
    servicesRu: 'Веб-дизайн / UI / Лендинг',
    intro: 'A modern landing page designed to effectively showcase balcony glazing and insulation services, building customer trust.',
    introRu: 'Современный лендинг для продвижения услуг по остеклению и утеплению балконов, укрепляющий доверие клиентов.',
    challenge: 'Create a clean, conversion-focused website that highlights expertise, special offers, and a vast portfolio of completed projects.',
    challengeRu: 'Создать чистый, конверсионный сайт, демонстрирующий экспертизу, спецпредложения и большое портфолио реализованных проектов.',
    solution: [
      ['UI DESIGN', 'Developed a trustworthy visual style using warm, interior-friendly colors and clear typography.'],
      ['CONVERSION', 'Strategically placed special offers and contact forms to maximize lead generation.'],
      ['PORTFOLIO', 'Built an immersive gallery to demonstrate the quality of over 100+ transformed balconies.'],
    ],
    solutionRu: [
      ['UI-ДИЗАЙН', 'Разработали доверительный визуальный стиль с тёплыми цветами и чёткой типографикой.'],
      ['КОНВЕРСИЯ', 'Стратегически разместили спецпредложения и формы для максимальной генерации лидов.'],
      ['ПОРТФОЛИО', 'Создали галерею, демонстрирующую качество более 100+ преображённых балконов.'],
    ],
    outcomes: ['INCREASED CONVERSION', 'CLEARER SERVICE SHOWCASE', 'MODERN WEB PRESENCE'],
    outcomesRu: ['РОСТ КОНВЕРСИИ', 'ЧЁТКАЯ ПОДАЧА УСЛУГ', 'СОВРЕМЕННОЕ ВЕБ-ПРИСУТСТВИЕ'],
    visual: 'visual-b',
  },
  {
    slug: 'woman-create',
    index: '03',
    name: 'WOMAN CREATE',
    meta: 'EVENT × DESIGN × WEB',
    year: '2026',
    industry: 'Events / Education',
    industryRu: 'Мероприятия / Образование',
    services: 'Event Branding / Web / UI',
    servicesRu: 'Брендинг события / Веб / UI',
    intro: "A digital platform for the biggest women's business festival, designed to convey emotion, community, and actionable business insights.",
    introRu: 'Цифровая платформа крупнейшего женского бизнес-фестиваля — передаёт эмоции, сообщество и практические бизнес-инсайты.',
    challenge: 'Balance a soft, inspiring aesthetic with clear event mechanics: selling tickets, showcasing speakers, and navigating festival zones.',
    challengeRu: 'Совместить мягкую вдохновляющую эстетику с чёткой механикой: продажа билетов, подача спикеров и навигация по зонам фестиваля.',
    solution: [
      ['BRAND EXPERIENCE', 'Integrated hand-written typography and warm tones to create a welcoming, personal atmosphere.'],
      ['TICKET FLOW', 'Designed an intuitive ticket purchase and program discovery journey.'],
      ['FESTIVAL ZONES', 'Created distinct visual modules for the Main Stage, Business Stage, and Wellness zones.'],
    ],
    solutionRu: [
      ['БРЕНД-ОПЫТ', 'Интегрировали рукописную типографику и тёплые оттенки для создания личной атмосферы.'],
      ['ПОКУПКА БИЛЕТОВ', 'Разработали интуитивный путь покупки билетов и знакомства с программой.'],
      ['ЗОНЫ ФЕСТИВАЛЯ', 'Создали отдельные визуальные модули для Главной сцены, Бизнес-сцены и Wellness-зоны.'],
    ],
    outcomes: ['SOLD OUT EVENT', 'SEAMLESS MOBILE UX', 'EMOTIONAL CONNECTION'],
    outcomesRu: ['РАСПРОДАННОЕ МЕРОПРИЯТИЕ', 'ПЛАВНЫЙ МОБИЛЬНЫЙ UX', 'ЭМОЦИОНАЛЬНАЯ СВЯЗЬ'],
    visual: 'visual-c',
  },
  {
    slug: 'manharrdy',
    index: '04',
    name: 'MANHARRDY',
    meta: 'E-COMMERCE × FASHION × WEB',
    year: '2026',
    industry: 'Fashion / Retail',
    industryRu: 'Мода / Ритейл',
    services: 'E-commerce / UI / Frontend',
    servicesRu: 'E-commerce / UI / Фронтенд',
    intro: "A sleek digital storefront for an Almaty-based fashion brand, blending high-end editorial aesthetics with a frictionless shopping experience.",
    introRu: 'Элегантный цифровой магазин алматинского fashion-бренда — высокая эдиториальная эстетика и безупречный опыт покупки.',
    challenge: "Design an online boutique that reflects the brand's \"effortless elegance\" while providing a robust, fast, and scalable e-commerce catalogue.",
    challengeRu: 'Создать онлайн-бутик, отражающий «лёгкую элегантность» бренда, с надёжным, быстрым и масштабируемым каталогом.',
    solution: [
      ['VISUAL MERCHANDISING', 'Created a minimalist UI where photography and product details take center stage.'],
      ['CATALOGUE UX', 'Implemented intuitive filtering, sorting, and seamless navigation for the new collections.'],
      ['BRAND IDENTITY', 'Used a refined monochromatic palette and elegant typography to elevate the shopping experience.'],
    ],
    solutionRu: [
      ['ВИЗУАЛЬНЫЙ МЕРЧАНДАЙЗИНГ', 'Создали минималистичный UI, где фотографии и детали товаров в центре внимания.'],
      ['UX КАТАЛОГА', 'Реализовали интуитивную фильтрацию, сортировку и навигацию для новых коллекций.'],
      ['ФИРМЕННЫЙ СТИЛЬ', 'Использовали монохромную палитру и изящную типографику для возвышения опыта покупки.'],
    ],
    outcomes: ['PREMIUM STOREFRONT', 'FRICTIONLESS CHECKOUT', 'ENHANCED BRAND PERCEPTION'],
    outcomesRu: ['ПРЕМИАЛЬНАЯ ВИТРИНА', 'УДОБНАЯ ОПЛАТА', 'УСИЛЕННОЕ ВОСПРИЯТИЕ БРЕНДА'],
    visual: 'visual-d',
  },
];
