export const projects = [
  {
    slug: 'ma-store',
    index: '01',
    name: 'DAR GROUP',
    meta: 'CORPORATE × UX/UI × WEB',
    year: '2026',
    industry: 'Retail / Fashion',
    services: 'UX/UI / Frontend / E-commerce',
    intro: 'Digital storefront built around a clean catalogue, strong product presentation and frictionless purchase flow.',
    challenge: 'Create a modern e-commerce experience that feels premium without becoming decorative or difficult to use.',
    solution: [
      ['UX ARCHITECTURE', 'Restructured catalogue, navigation and product paths around fast decision making.'],
      ['VISUAL SYSTEM', 'Built a restrained interface language where product content remains the hero.'],
      ['DEVELOPMENT', 'Created a responsive component system ready for growth and new collections.'],
    ],
    outcomes: ['SCALABLE UI SYSTEM', 'RESPONSIVE STORE', 'FASTER PRODUCT DISCOVERY'],
    visual: 'visual-a',
  },
  {
    slug: 'jaryq-home',
    index: '02',
    name: 'JARYQ HOME',
    meta: 'CONSTRUCTION × UX/UI × WEB',
    year: '2026',
    industry: 'Construction / Glazing',
    services: 'Web Design / UI / Landing',
    intro: 'A modern landing page designed to effectively showcase balcony glazing and insulation services, building customer trust.',
    challenge: 'Create a clean, conversion-focused website that highlights expertise, special offers, and a vast portfolio of completed projects.',
    solution: [
      ['UI DESIGN', 'Developed a trustworthy visual style using warm, interior-friendly colors and clear typography.'],
      ['CONVERSION', 'Strategically placed special offers and contact forms to maximize lead generation.'],
      ['PORTFOLIO', 'Built an immersive gallery to demonstrate the quality of over 100+ transformed balconies.'],
    ],
    outcomes: ['INCREASED CONVERSION', 'CLEARER SERVICE SHOWCASE', 'MODERN WEB PRESENCE'],
    visual: 'visual-b',
  },
  {
    slug: 'woman-create',
    index: '03',
    name: 'WOMAN CREATE',
    meta: 'EVENT × DESIGN × WEB',
    year: '2026',
    industry: 'Events / Education',
    services: 'Event Branding / Web / UI',
    intro: 'A digital platform for the biggest women\'s business festival, designed to convey emotion, community, and actionable business insights.',
    challenge: 'Balance a soft, inspiring aesthetic with clear event mechanics: selling tickets, showcasing speakers, and navigating festival zones.',
    solution: [
      ['BRAND EXPERIENCE', 'Integrated hand-written typography and warm tones to create a welcoming, personal atmosphere.'],
      ['TICKET FLOW', 'Designed an intuitive ticket purchase and program discovery journey.'],
      ['FESTIVAL ZONES', 'Created distinct visual modules for the Main Stage, Business Stage, and Wellness zones.'],
    ],
    outcomes: ['SOLD OUT EVENT', 'SEAMLESS MOBILE UX', 'EMOTIONAL CONNECTION'],
    visual: 'visual-c',
  },
  {
    slug: 'manharrdy',
    index: '04',
    name: 'MANHARRDY',
    meta: 'E-COMMERCE × FASHION × WEB',
    year: '2026',
    industry: 'Fashion / Retail',
    services: 'E-commerce / UI / Frontend',
    intro: 'A sleek digital storefront for an Almaty-based fashion brand, blending high-end editorial aesthetics with a frictionless shopping experience.',
    challenge: 'Design an online boutique that reflects the brand\'s "effortless elegance" while providing a robust, fast, and scalable e-commerce catalogue.',
    solution: [
      ['VISUAL MERCHANDISING', 'Created a minimalist UI where photography and product details take center stage.'],
      ['CATALOGUE UX', 'Implemented intuitive filtering, sorting, and seamless navigation for the new collections.'],
      ['BRAND IDENTITY', 'Used a refined monochromatic palette and elegant typography to elevate the shopping experience.'],
    ],
    outcomes: ['PREMIUM STOREFRONT', 'FRICTIONLESS CHECKOUT', 'ENHANCED BRAND PERCEPTION'],
    visual: 'visual-d',
  },
];
